export LOCAL_BIN="$HOME/.dotfiles/env/work/bin"
export PATH="$LOCAL_BIN:$PATH"
export PATH="/Library/Frameworks/Python.framework/Versions/Current/bin:$PATH"
export PATH="/etc/profiles/per-user/wojciechkozyra/bin:$PATH"

alias eas_dev=$HOME/expo/eas-cli/bin/run
alias eas_local=$HOME/.dotfiles/env/$CURRENT_ENV/eas_local.sh

export DISABLE_NVM=1
export VOLTA_HOME="$HOME/.volta"
grep --silent "$VOLTA_HOME/bin" <<< $PATH || export PATH="$VOLTA_HOME/bin:$PATH"

MYCLI_ZSH_SETUP_PATH=/Users/wojciechkozyra/.cache/mycli/completion/zsh_setup && test -f $MYCLI_ZSH_SETUP_PATH && source $MYCLI_ZSH_SETUP_PATH;
EAS_AC_ZSH_SETUP_PATH=/Users/wojciechkozyra/Library/Caches/eas-cli/autocomplete/zsh_setup && test -f $EAS_AC_ZSH_SETUP_PATH && source $EAS_AC_ZSH_SETUP_PATH;
