keyboard.bindings = [
    { action = "Paste", key = "Paste" },
    { action = "Copy", key = "Copy" },
    { action = "ClearLogNotice", key = "L", mods = "Control"},
    { chars = "\f", key = "L", mode = "~Vi|~Search", mods = "Control" },
    { action = "ScrollPageUp", key = "PageUp", mode = "~Alt", mods = "Shift" },
    { action = "ScrollPageDown", key = "PageDown", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToTop", key = "Home", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToBottom", key = "End", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToBottom", key = "Space", mode = "Vi|~Search", mods = "Shift|Control" },
    { action = "ToggleViMode", key = "Space", mode = "~Search", mods = "Shift|Control" },
    { action = "ClearSelection", key = "Escape", mode = "Vi|~Search" },
    { action = "ScrollToBottom", key = "I", mode = "Vi|~Search" },
    { action = "ToggleViMode", key = "I", mode = "Vi|~Search" },
    { action = "ToggleViMode", key = "C", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollLineUp", key = "Y", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollLineDown", key = "E", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollToTop", key = "G", mode = "Vi|~Search" },
    { action = "ScrollToBottom", key = "G", mode = "Vi|~Search", mods = "Shift" },
    { action = "ScrollPageUp", key = "B", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollPageDown", key = "F", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollHalfPageUp", key = "U", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollHalfPageDown", key = "D", mode = "Vi|~Search", mods = "Control" },
    { action = "Copy", key = "Y", mode = "Vi|~Search" },
    { action = "ClearSelection", key = "Y", mode = "Vi|~Search" },
    { action = "ClearSelection", key = "Copy", mode = "Vi|~Search" },
    { action = "Open", key = "Return", mode = "Vi|~Search" },
    { action = "Up", key = "K", mode = "Vi|~Search" },
    { action = "Down", key = "J", mode = "Vi|~Search" },
    { action = "Left", key = "H", mode = "Vi|~Search" },
    { action = "Right", key = "L", mode = "Vi|~Search" },
    { action = "Up", key = "Up", mode = "Vi|~Search" },
    { action = "Down", key = "Down", mode = "Vi|~Search" },
    { action = "Left", key = "Left", mode = "Vi|~Search" },
    { action = "Right", key = "Right", mode = "Vi|~Search" },
    { action = "First", key = "Key0", mode = "Vi|~Search" },
    { action = "Last", key = "Key4", mode = "Vi|~Search", mods = "Shift" },
    { action = "FirstOccupied", key = "Key6", mode = "Vi|~Search", mods = "Shift" },
    { action = "High", key = "H", mode = "Vi|~Search", mods = "Shift" },
    { action = "Middle", key = "M", mode = "Vi|~Search", mods = "Shift" },
    { action = "Low", key = "L", mode = "Vi|~Search", mods = "Shift" },
    { action = "SemanticLeft", key = "B", mode = "Vi|~Search" },
    { action = "SemanticRight", key = "W", mode = "Vi|~Search" },
    { action = "SemanticRightEnd", key = "E", mode = "Vi|~Search" },
    { action = "WordLeft", key = "B", mode = "Vi|~Search", mods = "Shift" },
    { action = "WordRight", key = "W", mode = "Vi|~Search", mods = "Shift" },
    { action = "WordRightEnd", key = "E", mode = "Vi|~Search", mods = "Shift" },
    { action = "Bracket", key = "Key5", mode = "Vi|~Search", mods = "Shift" },
    { action = "SearchForward", key = "Slash", mode = "Vi|~Search" },
    { action = "SearchBackward", key = "Slash", mode = "Vi|~Search", mods = "Shift" },
    { action = "SearchNext", key = "N", mode = "Vi|~Search" },
    { action = "SearchPrevious", key = "N", mode = "Vi|~Search", mods = "Shift" },
    { action = "SearchConfirm", key = "Return", mode = "Search|Vi" },
    { action = "SearchCancel", key = "Escape", mode = "Search" },
    { action = "SearchCancel", key = "C", mode = "Search", mods = "Control" },
    { action = "SearchClear", key = "U", mode = "Search", mods = "Control" },
    { action = "SearchDeleteWord", key = "W", mode = "Search", mods = "Control" },
    { action = "SearchHistoryPrevious", key = "P", mode = "Search", mods = "Control" },
    { action = "SearchHistoryNext", key = "N", mode = "Search", mods = "Control" },
    { action = "SearchHistoryPrevious", key = "Up", mode = "Search" },
    { action = "SearchHistoryNext", key = "Down", mode = "Search" },
    { action = "SearchFocusNext", key = "Return", mode = "Search|~Vi" },
    { action = "SearchFocusPrevious", key = "Return", mode = "Search|~Vi", mods = "Shift" },
    { action = "ToggleNormalSelection", key = "V", mode = "Vi|~Search" },
    { action = "ToggleLineSelection", key = "V", mode = "Vi|~Search", mods = "Shift" },
    { action = "ToggleBlockSelection", key = "V", mode = "Vi|~Search", mods = "Control" },
    { action = "ToggleSemanticSelection", key = "V", mode = "Vi|~Search", mods = "Alt" },
    { chars = "i", key = "V", mode = "Vi", mods = "Control|Shift" },
    { action = "Paste", key = "V", mode = "Vi", mods = "Control|Shift" },
    { action = "Paste", key = "V", mode = "~Vi", mods = "Control|Shift" },
    { action = "Copy", key = "C", mods = "Control|Shift" },
    { action = "SearchForward", key = "F", mode = "~Search", mods = "Control|Shift" },
    { action = "SearchBackward", key = "B", mode = "~Search", mods = "Control|Shift" },
    { action = "ClearSelection", key = "C", mode = "Vi|~Search", mods = "Control|Shift" },
    { action = "PasteSelection", key = "Insert", mods = "Shift" },
    { action = "ResetFontSize", key = "Key0", mods = "Control" },
    { action = "IncreaseFontSize", key = "Equals", mods = "Control" },
    { action = "IncreaseFontSize", key = "Plus", mods = "Control" },
    { action = "IncreaseFontSize", key = "NumpadAdd", mods = "Control" },
    { action = "DecreaseFontSize", key = "Minus", mods = "Control" },
    { action = "DecreaseFontSize", key = "NumpadSubtract", mods = "Control" },
    { action = "None", key = "Return", mods = "Alt" },
    { action = "None", key = "K", mode = "~Vi|~Search", mods = "Command" },
    { action = "None", key = "K", mode = "~Vi|~Search", mods = "Command" },
    { action = "None", key = "Key0", mods = "Command" },
    { action = "None", key = "Equals", mods = "Command" },
    { action = "None", key = "Plus", mods = "Command" },
    { action = "None", key = "NumpadAdd", mods = "Command" },
    { action = "None", key = "Minus", mods = "Command" },
    { action = "None", key = "NumpadSubtract", mods = "Command" },
    { action = "None", key = "V", mods = "Command" },
    { action = "None", key = "C", mods = "Command" },
    { action = "None", key = "C", mode = "Vi|~Search", mods = "Command" },
    { action = "None", key = "H", mods = "Command" },
    { action = "None", key = "H", mods = "Command|Alt" },
    { action = "None", key = "M", mods = "Command" },
    { action = "None", key = "Q", mods = "Command" },
    { action = "None", key = "W", mods = "Command" },
    { action = "None", key = "N", mods = "Command" },
    { action = "None", key = "F", mods = "Command|Control" },
    { action = "None", key = "F", mode = "~Search", mods = "Command" },
    { action = "None", key = "B", mode = "~Search", mods = "Command"}
]

[terminal]

[cursor]
blink_interval = 750
unfocused_hollow = true
vi_mode_style = "None"

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e7c547"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[colors.footer_bar]
background = "#c5c8c6"
foreground = "#1d1f21"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Medium"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000
multiplier = 5

[terminal.shell]
args = ["--login"]
program = "zsh"

[window]
decorations_theme_variant = "Dark"
dynamic_padding = false

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 4
