ZSH_CUSTOM="$HOME/.dotfiles/configs/zsh"
ZSH_THEME="bira"
export HISTSIZE=500000
export SAVEHIST=500000
setopt appendhistory
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

plugins=(
    git common-aliases cp docker golang vi-mode vim-interaction
)

if [ -s $HOME/.oh-my-zsh ]; then
    ZSH=$HOME/.oh-my-zsh
fi
source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'
export GPG_TTY=$(tty)

export MOZ_ENABLE_WAYLAND=1

export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/Android/Sdk/platform-tools:$PATH"
export PATH="$HOME/Android/Sdk/tools:$PATH"
export PATH="$HOME/Android/Sdk/cmdline-tools/latest/bin:$PATH"

export PATH="$VOLTA_HOME/bin:$PATH"

export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
export ANDROID_HOME="$HOME/Android/Sdk"
export ANDROID_SDK="$HOME/Android/Sdk"

# Uncomment when working with huge repositories
# export DISABLE_UNTRACKED_FILES_DIRTY=true # improve performance on large repos

alias gti=git
alias g=git
alias ggpush='git push --set-upstream origin $(git_current_branch)'

function try_source() {
    test -s $1 && source $1
}

try_source $HOME/.zshrc.secrets

[ -x "$(command -v direnv)" ] && eval "$(direnv hook zsh)"

if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    export PATH="$HOME/.rvm/bin:$PATH"
    source $HOME/.rvm/scripts/rvm
fi

try_source $HOME/.cache/mycli/completion/zsh_setup
