export LOCAL_BIN="$HOME/.dotfiles/env/work/bin"

# The next line updates PATH for the Google Cloud SDK.
[ -f "$HOME/google-cloud-sdk/path.zsh.inc" ] && source "$HOME/google-cloud-sdk/path.zsh.inc"

# The next line enables shell command completion for gcloud.
[ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ] && source "$HOME/google-cloud-sdk/completion.zsh.inc"

alias eas_dev=$HOME/expo/eas-cli/packages/eas-cli/bin/run
alias eas_local=$HOME/.dotfiles/env/work/eas_local.sh
alias expo_global_dev=$HOME/expo/expo-cli/packages/expo-cli/bin/expo.js
alias expo_dev=$HOME/expo/expo/packages/@expo/cli/build/bin/cli

export TURTLE_V2_EXAMPLE_PRODUCTION_PROJECT_ID=cb6571a4-8457-45b9-9c4a-d489f63e4f1d
export TURTLE_V2_EXAMPLE_STAGING_PROJECT_ID=8098b803-f4b1-4f82-9960-390a4ab98fde
export TURTLE_V2_EXAMPLE_LOCAL_PROJECT_ID=""
export WWW_DISABLE_LOCAL_VOLTA=1
export EAS_BUILD_INTERNAL_EXECUTABLE="/home/wojtek/expo/eas-cli/packages/eas-cli/bin/run"

export DISABLE_NVM=1
export VOLTA_HOME="$HOME/.volta"
grep --silent "$VOLTA_HOME/bin" <<< $PATH || export PATH="$VOLTA_HOME/bin:$PATH"

MYCLI_ZSH_SETUP_PATH=/home/wojtek/.cache/mycli/completion/zsh_setup && test -f $MYCLI_ZSH_SETUP_PATH && source $MYCLI_ZSH_SETUP_PATH;
EAS_AC_ZSH_SETUP_PATH=/home/wojtek/.cache/eas-cli/autocomplete/zsh_setup && test -f $EAS_AC_ZSH_SETUP_PATH && source $EAS_AC_ZSH_SETUP_PATH;
compdef $HOME/expo/eas-cli/packages/eas-cli/bin/run='eas'
compdef $HOME/.dotfiles/env/work/eas_local.sh='eas'
