package hostd

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path"
	"strings"
)

const (
	DefaultStateDir = "/var/lib/hostd"

	tokenFile = "token"
)

// ReadToken returns the token generated by the server on its first start.
func ReadToken(stateDir string) (string, error) {
	content, err := os.ReadFile(path.Join(stateDir, tokenFile))
	if err != nil {
		return "", err
	}
	token := strings.TrimSpace(string(content))
	if token == "" {
		return "", fmt.Errorf("%s is empty", path.Join(stateDir, tokenFile))
	}
	return token, nil
}

// EnsureToken returns the token, generating it on the first call.
func EnsureToken(stateDir string) (string, error) {
	token, err := ReadToken(stateDir)
	if err == nil {
		return token, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return "", err
	}
	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	token = hex.EncodeToString(raw)
	if err := os.WriteFile(path.Join(stateDir, tokenFile), []byte(token+"\n"), 0o600); err != nil {
		return "", err
	}
	log.Info("Generated new token, read it with `sudo mycli hostd state`")
	return token, nil
}
